# clusters/my-cluster/flux-system/apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
