apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  values:
    replicaCount: 1
    ui:
      color: "#ff0000"
      message: "Dev Cluster"
